### PR TITLE
TFS 796145: Update Safeguard-ps to keep up with DirectoryRewrite

### PR DESCRIPTION
**Pull request by Goelrachit**
- Extended assets module and remove the directories module to accommodate API changes due to DirectoryRewrite
- Added backward compatibility to cmdlets in directory module to work with API v2
- Merge master to use -RetryVersion and -RetryUrl parameters

### CODE REVIEW

**Comment by petrsnd** [comment]
@Goelrachit 
We are going to need to rework this PR so that it doesn't have a bunch of my commits duplicated into it.  I can help with that when you're ready.

**Comment by Goelrachit** [comment]
I had rebased this branch with master and this PR is targeting OneIdentity/DirectoryApiV3 branh, which is not up-to-date with maser. That's why this PR shows your commits. Once this PR is merged and the "DirectoryApiV3" branch is merged to master, I think only my commits will show up. Also, if you change the target of this PR to "master" branch, only my commits are shown. So, I think it is fine the way it is?

**Comment by DanPeterson** [comment]
Ah.  I didn't notice the target not being for master.

**Comment by Goelrachit** [comment]
Oops I did it again !!. I opened a new PR to replace this one: #136

**Comment by Goelrachit** [comment]
Oops I did it again !!. I opened a new PR to replace this one: #136

**Pull request closed without merging**
